site_name: OpID Documentation
site_description: Documentation for project OpID
theme: mkdocs
pages: 
  - ['index.md', 'Background']
  - ['infrastructure.md', 'Infrastructure']
  - ['database.md', 'Database']
  - ['implementation.md', 'Implementation']
